[global]
duration = 1.2
shift = 100
easing = "expo"

[[global.layers]]
path = "/home/maka/blender/wallpaper/back_sky.png"
shift_multiplier = 0.2
opacity = 1.0
blur = 3.0

[[global.layers]]
path = "/home/maka/blender/wallpaper/back_2_mountainsBack.png"
shift_multiplier = 0.5
opacity = 1.0
blur = 1.5

[[global.layers]]
path = "/home/maka/blender/wallpaper/midle_mountains.png"
shift_multiplier = 1.0
opacity = 1.0
blur = 0.0

[[global.layers]]
path = "/home/maka/blender/wallpaper/front_flat.png"
shift_multiplier = 1.8
opacity = 1.0
blur = 0.0